### ISSUE TITLE
Duplicate data for sleep stages for different dates 

### ISSUE THREAD

**Issue by sashasomms** [orcasgit/python-fitbit#139]
I'm working on code to download FitBit data for a research study to CSV files for about 60 research participants. For multiple participants, duplicate data on sleep stages is given for consecutive days, despite there being different data for each day when I look through FitBit's web dashboard.  Any idea why this is happening? 

Here's an example:

```python
auth2_client = fitbit.Fitbit(CLIENT_ID, CLIENT_SECRET, oauth2=True, access_token=TokenDictCurrent['access_token'][0], refresh_token=TokenDictCurrent['refresh_token'][0], refresh_cb=refresh_cb)
d1 = '2018-03-20'
d2 = '2018-03-21'
fit_statsSleep_d1 = auth2_client.sleep(date=d1)
fit_statsSleep_d2 = auth2_client.sleep(date=d2)
fit_statsSleep_d1['summary']['stages']
fit_statsSleep_d2['summary']['stages']
```

Gives me:
```
>>> fit_statsSleep_d1['summary']['stages']
{u'light': 315, u'wake': 74, u'deep': 59, u'rem': 70}
>>> fit_statsSleep_d2['summary']['stages']
{u'light': 315, u'wake': 74, u'deep': 59, u'rem': 70}
```

When I look up sleep stages through the web dashboard, the data acquired above matches the data for 3/20, but 3/21 has different data in the web dashboard (and there is data for 3/21, so it's not just overwriting empty cells):

<img width="617" alt="screen shot 2018-09-18 at 5 43 35 pm" src="https://user-images.githubusercontent.com/7452307/45721363-624f6580-bb6d-11e8-8447-0f9fbf220832.png">
<img width="516" alt="screen shot 2018-09-18 at 5 43 50 pm" src="https://user-images.githubusercontent.com/7452307/45721362-624f6580-bb6d-11e8-9555-d563f0e57372.png">

**Comment by DanWebster** [comment]
I've seen the same thing.  You need to upgrade to at least the 1.2 version of the Fitbit API when initializing the API caller.  The current version (1.0) has sleep stage data that is either a stand in for data or it doesn't update each day. That should fix it, and from my own testing, doesn't affect the other API calls to data types like resting heart rate or intradayHR

**Comment by sashasomms** [comment]
Thanks for the quick response.
Huh, I just changed API version to 1.2 in the 2 places in api.py, started a new python session and reran the calls, but it still seems to be duplicating? 
'''
>>> auth2_client = fitbit.Fitbit(CLIENT_ID, CLIENT_SECRET, oauth2=True, access_token=TokenDictCurrent['access_token'][0], refresh_token=TokenDictCurrent['refresh_token'][0], refresh_cb=refresh_cb)
>>> d1 = '2018-03-20'
>>> d2 = '2018-03-21'
>>> fit_statsSleep_d1 = auth2_client.sleep(date=d1)
>>> fit_statsSleep_d2 = auth2_client.sleep(date=d2)
>>> fit_statsSleep_d1['summary']['stages']
{u'light': 315, u'wake': 74, u'deep': 59, u'rem': 70}
>>> fit_statsSleep_d2['summary']['stages']
{u'light': 315, u'wake': 74, u'deep': 59, u'rem': 70}
>>> auth2_client.API_VERSION
1.2
'''

**Comment by sashasomms** [comment]
Ah! Got it. Related to this:
https://community.fitbit.com/t5/Web-API-Development/API-returns-incorrect-sleep-stages-data/m-p/2482583 

They say:

> <JSON Response> -->Summary --> Stages
> 
> sleep stage data is always the same ( still havent figured out exactly what that is or why. Perhaps an average?)
> 
> "But the  <JSON Response> --> sleep -->levels --> Summary --> <light/wake/rem/deep> changed with the date ( this is only available when using API v.1.2 it seems ). This stage data was on par with what the Official Fitbit app was showing me, so I took it as being accurate."

So 
fit_statsSleep_d2['summary']['stages'] is still wrong, 
but 
fit_statsSleep_d2['sleep'][0]['levels']['summary']['light']['minutes']
Matches the web dash (and wasn't accessible with API_VERSION 1). 

Thanks for your help!

**Comment by DanWebster** [comment]
Yes, and good call on the alternate endpoint; I forgot to mention that.  Very glad you have it working
